# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZeroBeta Trading & Research
email: contact@zerobeta.com.br
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zerobetatr.github.io" # the base hostname & protocol for your site
github_username:  ZeroBetaTR
logo: "/img/logo.png"
contact_text: > #
  Estamos sempre disponíveis para esclarecer qualquer dúvida sobre nosso negócio.
  Além disso, estamos sempre dispostos a conversar sobre idéias, sugestões e oportunidades
  de negócios.
address: Rua Marins Alvarino, 150 - Itararé. Vitória - ES
telephone: (27) 2904.7660

# Locations
base_imgpath_team: "/img/team/"

# Build settings
markdown: kramdown

collections:
  - solutions
