# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: ZeroBeta Trading & Research
email: zerobeta@zerobeta.com.br
description: > # this means to ignore newlines until "baseurl:"
  ZeroBeta develops algorithmic trading solutions based on cutting edge machine
  learning techniques. The solutions are commercialized through Robot as a Service
   portals allowing our team to focus on R&D."
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zerobetatr.github.io" # the base hostname & protocol for your site
github_username:  ZeroBetaTR
facebook: zerobetatrading
logo: "/img/logo.png"
contact_text: > #
  Estamos sempre disponíveis para esclarecer qualquer dúvida sobre nosso negócio.
  Além disso, estamos sempre dispostos a conversar sobre idéias, sugestões e oportunidades
  de negócios.
address: Rua Marins Alvarino, 150 - Itararé. Vitória - ES
telephone: (27) 2904.7660
mission: > #
  Desenvolver sistemas de negociação utilizando utilizando técnicas de
  inteligência artificial entregando à investidores de Forex, ações,
  mercadorias e futuros rentabilidade superior aos índices de mercado.
vision: > #
  Ser referência entre signal providers do ZuluTrade e vendors do
  MetaTrader Market.
values: > #
  Pessoas excelentes trabalhando com paixão como uma equipe buscando
  inovação e desempenho.


# Locations
base_imgpath_team: "/img/team/"
base_imgpath_parnters: "/img/partners/"

# Build settings
markdown: kramdown

collections:
  - solutions
